# Generated by Django 4.0.5 on 2022-06-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cajas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rf',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unidades',
            field=models.IntegerField(default=0),
        ),
    ]
